# Generated by Django 4.2.7 on 2023-12-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_alter_compra_usuario_parceria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parceria',
        ),
    ]
