# Generated by Django 4.2.7 on 2023-12-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_alter_avaliacao_usuario_alter_avaliacao_vendedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='quantidade_produto',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
