# Generated by Django 4.2.7 on 2023-12-08 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0004_rename_vedendor_produto_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Artesanato',
            fields=[
                ('categoria_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.categoria')),
            ],
            bases=('home.categoria',),
        ),
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('categoria_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.categoria')),
            ],
            bases=('home.categoria',),
        ),
        migrations.CreateModel(
            name='Doce',
            fields=[
                ('categoria_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.categoria')),
            ],
            bases=('home.categoria',),
        ),
        migrations.CreateModel(
            name='Gelado',
            fields=[
                ('categoria_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.categoria')),
            ],
            bases=('home.categoria',),
        ),
        migrations.CreateModel(
            name='Moda',
            fields=[
                ('categoria_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.categoria')),
            ],
            bases=('home.categoria',),
        ),
        migrations.CreateModel(
            name='Salgado',
            fields=[
                ('categoria_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.categoria')),
            ],
            bases=('home.categoria',),
        ),
    ]
