# Generated by Django 4.2.7 on 2023-12-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bebida',
            name='categoria_ptr',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='doce',
            name='categoria_ptr',
        ),
        migrations.RemoveField(
            model_name='gelado',
            name='categoria_ptr',
        ),
        migrations.RemoveField(
            model_name='moda',
            name='categoria_ptr',
        ),
        migrations.RemoveField(
            model_name='salgado',
            name='categoria_ptr',
        ),
        migrations.DeleteModel(
            name='Artesanato',
        ),
        migrations.DeleteModel(
            name='Bebida',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Doce',
        ),
        migrations.DeleteModel(
            name='Gelado',
        ),
        migrations.DeleteModel(
            name='Moda',
        ),
        migrations.DeleteModel(
            name='Salgado',
        ),
    ]
