# Generated by Django 4.2.7 on 2023-12-05 14:16

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('matricula', models.CharField(max_length=30, unique=True)),
                ('telefone', models.CharField(default='', max_length=20)),
                ('foto', models.ImageField(default='foto_usuario/imagem_usuario_padrão.jpg', upload_to='foto_usuario')),
            ],
            options={
                'verbose_name': 'Usuário Comprador',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('matricula', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('telefone', models.CharField(default='', max_length=20)),
                ('foto', models.ImageField(default='foto_vendedor/imagem_usuario_padrão.jpg', upload_to='foto_vendedor')),
                ('negocio', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Usuário Vendedor',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_serv', models.CharField(max_length=32)),
                ('descricao_serv', models.TextField(max_length=50)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prod', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=150)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=9)),
                ('foto_prod', models.ImageField(default='', upload_to='foto_produto')),
                ('vedendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.vendedor')),
            ],
        ),
    ]
