# Generated by Django 4.2.7 on 2023-12-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuários Compradore'},
        ),
        migrations.AlterModelOptions(
            name='vendedor',
            options={'verbose_name': 'Usuários Vendedore'},
        ),
        migrations.AddField(
            model_name='vendedor',
            name='descrição',
            field=models.TextField(blank=True, default='Descrição do seu negócio.', max_length=500, null=True),
        ),
    ]
