# Generated by Django 4.2.7 on 2023-12-02 21:54

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendedor',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='vendedor',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='sobrenome',
        ),
        migrations.AddField(
            model_name='vendedor',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=12, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='foto_usuario/imagem_usuario_padrão.jpg', upload_to='foto_usuario'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='foto',
            field=models.ImageField(default='foto_vendedor/imagem_usuario_padrão.jpg', upload_to='foto_vendedor'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='telefone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
