# Generated by Django 4.2.7 on 2023-12-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_vendedor_options_alter_vendedor_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto_prod',
            field=models.ImageField(default='', upload_to='foto_produto'),
        ),
    ]
