# Generated by Django 4.2.7 on 2023-12-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_usuario_options_alter_vendedor_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendedor',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
