# Generated by Django 4.2.7 on 2023-12-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_alter_produto_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('artesanato', 'Artesanato'), ('doce', 'Doce'), ('moda', 'Moda'), ('salgado', 'Salgado'), ('bebida', 'Bebida'), ('gelado', 'Gelado')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='categorias',
            field=models.ManyToManyField(related_name='produtos', to='cadastro.categoria'),
        ),
    ]
